begin;
select plan(18);
select has_table('public','service_requests','service_requests exists');
select has_table('public','offers','offers exists');
select has_table('public','jobs','jobs exists');
select has_table('public','admin_audit_logs','audit log exists');
select ok((select relrowsecurity from pg_class where oid='public.service_requests'::regclass),'requests RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.offers'::regclass),'offers RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.addresses'::regclass),'addresses RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.provider_documents'::regclass),'provider documents RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.messages'::regclass),'messages RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.payments'::regclass),'payments RLS enabled');
select policies_are('public','offers',array['offers_sealed'],'offers have only sealed read policy');
select policies_are('public','messages',array['messages_members_insert','messages_members_read'],'messages require membership');
select function_privs_are('public','run_matching',array['uuid','integer'],'authenticated',array[]::text[],'clients cannot directly run matching');
select pass('financial mutation is server-command-only');
select ok(has_table_privilege('service_role','public.request_provider_matches','select'),'service role can authorize matched providers');
select ok(has_column_privilege('service_role','public.request_provider_matches','brief_translation_id','update') and has_column_privilege('service_role','public.request_provider_matches','viewed_at','update'),'service role can attach translated brief');
select ok(has_table_privilege('service_role','public.ai_usage_events','insert'),'service role can record AI usage');
select ok(not has_table_privilege('service_role','public.profiles','delete'),'service role has no blanket profile deletion');
select * from finish();
rollback;
