packages:
  - apps/*
  - packages/*

allowBuilds:
  libxmljs2: true

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.16'
  - '@expo/config@57.0.8'
  - '@expo/fingerprint@0.20.8'
  - '@expo/inline-modules@0.1.6'
  - '@expo/log-box@57.0.3'
  - '@expo/metro-runtime@57.0.11'
  - expo-asset@57.0.12
  - expo-constants@57.0.12
  - expo-image-picker@57.0.11
  - expo-location@57.0.11
  - expo-notifications@57.0.12
  - expo-router@57.0.14
  - expo@57.0.14

onlyBuiltDependencies:
  - esbuild
  - sharp
  - libxmljs2
  - supabase
