Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 0.0.0.0
StreamMaxLength 20M
MaxThreads 2
MaxConnectionQueueLength 2
MaxQueue 2
ReadTimeout 120
CommandReadTimeout 5
SendBufTimeout 5
MaxScanTime 120000
ExitOnOOM yes
LogTime yes
LogClean yes
LogVerbose no
ExtendedDetectionInfo no
AlertEncrypted yes
ScanArchive yes
ScanMail no
ScanHTML yes
ScanOLE2 yes
ScanPDF yes
ScanSWF yes
ScanXMLDOCS yes
ScanHWP3 yes
Bytecode yes
